/**
 * Metadata and JSON-LD builders.
 *
 * Every route composes its metadata from `pageMetadata` so canonical URLs, Open Graph
 * and Twitter cards cannot be forgotten on a page-by-page basis.
 */

import type { Metadata } from 'next'
import { SITE, absolute } from './site'
import {
  averageRating,
  categoryName,
  contentMix,
  formatPrice,
  instructorFor,
  ratingsCount,
  totalHours,
  totalMinutes,
  type Course,
} from '@/data/courses'

interface PageMetaInput {
  title: string
  description: string
  /** Route path, e.g. `/courses`. Becomes the canonical URL. */
  path: string
  image?: string
  imageAlt?: string
  type?: 'website' | 'article'
}

export function pageMetadata({
  title,
  description,
  path,
  image,
  imageAlt,
  type = 'website',
}: PageMetaInput): Metadata {
  const url = absolute(path)

  /*
    The `images` key is spread in only when there is one, never set to
    `undefined`. Declaring `openGraph.images` at all — even as undefined —
    counts as the route taking ownership of its share image, which suppresses
    the one generated by `opengraph-image.tsx`. Omitting the key lets the file
    convention supply it: the site card for most routes, the per-course card on
    a course page.
  */
  const images = image ? [{ url: image, width: 1200, height: 630, alt: imageAlt ?? title }] : null

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type,
      url,
      title,
      description,
      siteName: SITE.name,
      locale: SITE.locale,
      ...(images ? { images } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      ...(image ? { images: [image] } : {}),
    },
  }
}

/* ------------------------------------------------------------------------ */
/* JSON-LD                                                                   */
/* ------------------------------------------------------------------------ */

export interface Crumb {
  name: string
  path: string
}

export function breadcrumbLd(crumbs: Crumb[]): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: absolute(crumb.path),
    })),
  }
}

export function faqLd(items: { question: string; answerText: string }[]): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answerText },
    })),
  }
}

/** ISO 8601 duration, which is what `timeRequired` and `courseWorkload` expect. */
function isoDuration(minutes: number): string {
  const h = Math.floor(minutes / 60)
  const m = minutes % 60
  return `PT${h > 0 ? `${h}H` : ''}${m > 0 ? `${m}M` : ''}` || 'PT0M'
}

/**
 * Course + hasCourseInstance + AggregateRating.
 *
 * `hasCourseInstance` is required by Google for a Course rich result: without at least
 * one instance carrying a `courseMode` and a workload, the entity is dropped.
 */
export function courseLd(course: Course): Record<string, unknown> {
  const instructor = instructorFor(course)
  const mix = contentMix(course)
  const projectHours = mix.find((m) => m.kind === 'project')?.hours ?? 0

  return {
    '@context': 'https://schema.org',
    '@type': 'Course',
    '@id': absolute(`/courses/${course.slug}#course`),
    name: course.title,
    description: course.subtitle,
    url: absolute(`/courses/${course.slug}`),
    image: course.cover,
    inLanguage: 'en',
    dateModified: course.updatedAt,
    educationalLevel: course.level,
    about: course.tags,
    teaches: course.outcomes.map((outcome) => `${outcome.title}: ${outcome.detail}`),
    keywords: [categoryName(course.category), ...course.tags].join(', '),
    timeRequired: isoDuration(totalMinutes(course)),
    numberOfCredits: projectHours,
    provider: {
      '@type': 'Organization',
      name: SITE.name,
      url: SITE.url,
    },
    instructor: {
      '@type': 'Person',
      name: instructor.name,
      description: instructor.role,
      image: instructor.avatar,
    },
    offers: {
      '@type': 'Offer',
      price: course.price,
      priceCurrency: 'USD',
      category: course.price === 0 ? 'Free' : 'Paid',
      availability: 'https://schema.org/InStock',
      url: absolute(`/courses/${course.slug}`),
    },
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: averageRating(course),
      ratingCount: ratingsCount(course),
      reviewCount: course.reviews.length,
      bestRating: 5,
      worstRating: 1,
    },
    hasCourseInstance: [
      {
        '@type': 'CourseInstance',
        courseMode: 'Online',
        courseWorkload: isoDuration(totalMinutes(course)),
        name: `${course.title} — self-paced`,
        description: `Self-paced online cohort. ${totalHours(course)} hours of material, ${formatPrice(course.price)}.`,
        instructor: { '@type': 'Person', name: instructor.name },
        offers: {
          '@type': 'Offer',
          price: course.price,
          priceCurrency: 'USD',
          availability: 'https://schema.org/InStock',
        },
      },
    ],
    review: course.reviews.map((review) => ({
      '@type': 'Review',
      author: { '@type': 'Person', name: review.author },
      datePublished: review.postedAt,
      reviewBody: review.body,
      reviewRating: {
        '@type': 'Rating',
        ratingValue: review.rating,
        bestRating: 5,
        worstRating: 1,
      },
    })),
  }
}

/**
 * The catalogue as an ordered list of courses.
 *
 * `ItemList` is what lets a search engine understand /courses as a collection
 * rather than eight unrelated links, and each entry carries enough of the course
 * to be useful on its own without duplicating the full `Course` entity that
 * lives on the course page.
 */
export function courseListLd(courses: Course[]): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    '@id': absolute('/courses#catalogue'),
    name: 'SkillForge course catalogue',
    description: `All ${courses.length} SkillForge courses, with category, level, price and rating.`,
    numberOfItems: courses.length,
    itemListOrder: 'https://schema.org/ItemListOrderDescending',
    itemListElement: courses.map((course, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      item: {
        '@type': 'Course',
        '@id': absolute(`/courses/${course.slug}#course`),
        name: course.title,
        description: course.subtitle,
        url: absolute(`/courses/${course.slug}`),
        image: course.cover,
        educationalLevel: course.level,
        provider: { '@type': 'Organization', name: SITE.name, url: SITE.url },
        offers: {
          '@type': 'Offer',
          price: course.price,
          priceCurrency: 'USD',
          category: course.price === 0 ? 'Free' : 'Paid',
          availability: 'https://schema.org/InStock',
        },
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue: averageRating(course),
          ratingCount: ratingsCount(course),
          bestRating: 5,
          worstRating: 1,
        },
      },
    })),
  }
}

/** The organisation behind the catalogue, emitted once from the root layout. */
export function organisationLd(): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    '@id': absolute('/#organisation'),
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    slogan: SITE.tagline,
    sameAs: [SITE.repo],
  }
}

/** Site-level search action, so a catalogue search can surface in results. */
export function websiteLd(): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': absolute('/#website'),
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    publisher: { '@id': absolute('/#organisation') },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: absolute('/courses?q={search_term_string}'),
      },
      'query-input': 'required name=search_term_string',
    },
  }
}
